export const Operation = {
  PrintJob: 0x0002,
  ValidateJob: 0x0004,
  CreateJob: 0x0005,
  SendDocument: 0x0006,
  CancelJob: 0x0008,
  GetJobAttributes: 0x0009,
  GetJobs: 0x000A,
  GetPrinterAttributes: 0x000B,
  IdentifyPrinter: 0x003C,
} as const;

export const STATUS_NAMES: Record<number, string> = {
  0x0000: "successful-ok",
  0x0001: "successful-ok-ignored-or-substituted-attributes",
  0x0002: "successful-ok-conflicting-attributes",
  0x0400: "client-error-bad-request",
  0x0401: "client-error-forbidden",
  0x0402: "client-error-not-authenticated",
  0x0403: "client-error-not-authorized",
  0x0404: "client-error-not-possible",
  0x0405: "client-error-timeout",
  0x0406: "client-error-not-found",
  0x0407: "client-error-gone",
  0x0408: "client-error-request-entity-too-large",
  0x0409: "client-error-request-value-too-long",
  0x040A: "client-error-document-format-not-supported",
  0x040B: "client-error-attributes-or-values-not-supported",
  0x040C: "client-error-uri-scheme-not-supported",
  0x040D: "client-error-charset-not-supported",
  0x040E: "client-error-conflicting-attributes",
  0x040F: "client-error-compression-not-supported",
  0x0410: "client-error-compression-error",
  0x0411: "client-error-document-format-error",
  0x0412: "client-error-document-access-error",
  0x0413: "client-error-attributes-not-settable",
  0x0414: "client-error-ignore-all-subscriptions",
  0x0415: "client-error-too-many-subscriptions",
  0x0418: "client-error-document-password-error",
  0x0419: "client-error-document-permission-error",
  0x041A: "client-error-document-security-error",
  0x041B: "client-error-document-unprintable-error",
  0x041C: "client-error-account-info-needed",
  0x041D: "client-error-account-closed",
  0x041E: "client-error-account-limit-reached",
  0x041F: "client-error-account-authorization-failed",
  0x0420: "client-error-not-fetchable",
  0x0500: "server-error-internal-error",
  0x0501: "server-error-operation-not-supported",
  0x0502: "server-error-service-unavailable",
  0x0503: "server-error-version-not-supported",
  0x0504: "server-error-device-error",
  0x0505: "server-error-temporary-error",
  0x0506: "server-error-not-accepting-jobs",
  0x0507: "server-error-busy",
  0x0508: "server-error-job-canceled",
  0x0509: "server-error-multiple-document-jobs-not-supported",
  0x050A: "server-error-printer-is-deactivated",
  0x050B: "server-error-too-many-jobs",
  0x050C: "server-error-too-many-documents",
};

export function statusName(code: number): string {
  return STATUS_NAMES[code] ?? `0x${code.toString(16).padStart(4, "0")}`;
}

export const JOB_STATES: Record<number, string> = {
  3: "pending",
  4: "pending-held",
  5: "processing",
  6: "processing-stopped",
  7: "canceled",
  8: "aborted",
  9: "completed",
};

export const TERMINAL_JOB_STATES: ReadonlySet<string> = new Set(["canceled", "aborted", "completed"]);
